name: ID Fixup

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{ secrets.BOT_GITHUB_TOKEN }}
        fetch-depth: 0

    - name: Setup Git
      run: |
        git config --global user.name "AnkiTUM-Bot"
        git config --global user.email ${{ secrets.BOT_GITHUB_EMAIL }}

    - name: Run ID Fixup Script
      run: |
        pip install -r .github/workflows/requirements.txt --user
        python3 .github/workflows/id_fixup.py

    - name: Commit and Push Changes
      run: |
        git add .
        git commit -m "Auto-fixup IDs by GitHub Actions"
        git push
